services:
  - type: web
    name: pzu-backend
    env: docker # Usa o Dockerfile que criamos
    rootDir: backend # Aponta para a pasta do backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pzu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000

databases:
  - name: pzu-db
    plan: free
    postgresRole: pzu_admin
